services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:CHnQCPujAyrMdvBvNBufqCEHTXIWfvwC@switchback.proxy.rlwy.net:34792/railway?sslmode=require
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: inv
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: LuckyCode
    ports:
      - "6543:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
